name: "Publish Sonar JSON to CodeGuardian"
on:
  check_run:
    types: [completed]

permissions:
  contents: read
  id-token: write

jobs:
  share:
    name: Upload Sonar Results to CodeGuardian
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      - uses: pixee/upload-tool-results-action@v1
        with:
          tool: sonar
          pixee-api-url: https://ntt.pixee.ai
          sonar-token: ${{ secrets.SONAR_TOKEN }}
